
# Generación de otras vistas

Existen varios tipos de implementación de una interfaz de nombre `ViewResolver`, que nos ayudan a definir el tipo de vista a entregar:

* `AbstractCachingViewResolver`
* `AbstractTemplateViewResolver`
* `BeanNameViewResolver`
* `ContentNegotiatingViewResolver`
* `FreeMarkerViewResolver`
* `InternalResourceViewResolver`
* `JasperReportsViewResolver`
* `ResourceBundleViewResolver`
* `TilesViewResolver`
* `TilesViewResolver`
* `UrlBasedViewResolver`
* `VelocityLayoutViewResolver`
* `VelocityViewResolver`
* `XmlViewResolver`
* `XsltViewResolver`

Debemos considerar lo siguiente:

* SpringMVC soporta múltiples ViewResolvers
* Podemos sobreescribir vistas en ciertas circunstancias
* Solo los agregamos y si es necesario usamos el atributo order(en donde el valor más bajo tiene la precendencia más alta)
* Si ningún ViewResolver contiene la vista buscada, simplemente se arroja Exception

*WebConfig.java*
[source,java,linenums]
----
@Bean
public InternalResourceViewResolver internalResourceViewResolver() {
  InternalResourceViewResolver resolver = new InternalResourceViewResolver();
  resolver.setViewClass(JstlView.class);
  resolver.setPrefix("/WEB-INF/jsp/");
  resolver.setSuffix(".jsp");
  resolver.setOrder(10);
  return resolver;
}

@Bean
public BeanNameViewResolver beanNameViewResolver() {
  BeanNameViewResolver resolver = new BeanNameViewResolver();
  resolver.setOrder(0);
  return resolver;
}
----

* UserStoryExcelView.java*
[source,java,linenums]
----
package com.makingdevs.practica14;

import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import jxl.write.Label;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;

import org.springframework.stereotype.Component;
import org.springframework.web.servlet.view.document.AbstractJExcelView;

import com.makingdevs.model.UserStory;

@Component
public class UserStoryExcelView extends AbstractJExcelView {

  @Override
  protected void buildExcelDocument(Map<String, Object> model, WritableWorkbook workbook, HttpServletRequest request,
      HttpServletResponse response) throws Exception {
    WritableSheet sheet = workbook.createSheet("Tasks", 0);
    List<UserStory> userStories= (List<UserStory>) model.get("userStories");
    int i = 0;

    for (UserStory us : userStories) {
      sheet.addCell(new Label(0, i, String.valueOf(us.getId())));
      sheet.addCell(new Label(1,i,us.getDescription()));
      sheet.addCell(new Label(2,i,us.getEffort().toString()));
      sheet.addCell(new Label(3,i,us.getPriority().toString()));
      i++;
    }

  }
}
----

*UserStoryPdfView.java*
[source,java,linenums]
----
package com.makingdevs.practica14;

import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.stereotype.Component;
import org.springframework.web.servlet.view.document.AbstractPdfView;

import com.lowagie.text.Document;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;
import com.makingdevs.model.UserStory;

@Component
public class UserStoryPdfView extends AbstractPdfView {

  @Override
  protected void buildPdfDocument(Map<String, Object> model, Document document, PdfWriter writer,
      HttpServletRequest request, HttpServletResponse response) throws Exception {
    List<UserStory> userStories= (List<UserStory>) model.get("userStories");

    int i = 0;
    for (UserStory us : userStories) {
      document.addAuthor("makingdevs");
      document.addTitle("User Stories");
      String buffer = String.valueOf(us.getId());
      buffer += " - " + us.getDescription();
      document.add(new Paragraph(buffer));
      i++;
    }

  }

}
----

*UserStoryExportController.java*
[source,java,linenums]
----
package com.makingdevs.practica14;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;

import com.makingdevs.model.UserStory;
import com.makingdevs.services.UserStoryService;

@Controller
public class UserStoryExportController {

  @Autowired
  UserStoryService userStoryService;

  @RequestMapping("/project/{codeName}/userStory/exportToExcel")
  public String exportToExcel(@PathVariable("codeName") String codeName, Model model) {
    List<UserStory> userStories = userStoryService.findUserStoriesByProject(codeName);
    model.addAttribute("userStories", userStories);
    return "userStoryExcelView";
  }

  @RequestMapping("/project/{codeName}/userStory/exportToPdf")
  public String exportToPdf(@PathVariable("codeName") String codeName, Model model) {
    List<UserStory> userStories = userStoryService.findUserStoriesByProject(codeName);
    model.addAttribute("userStories", userStories);
    return "userStoryPdfView";
  }
}
----

Crea un par de vínculos para que puedas accederlos:

----
<a href="${pageContext.request.contextPath}/project/${project.codeName}/userStory/exportToExcel" class="btn btn-default"> Export to excel </a>
<a href="${pageContext.request.contextPath}/project/${project.codeName}/userStory/exportToPdf" class="btn btn-default"> Export to PDF </a>
----

TIP: Sin lugar a dudas, puedes comprobar el uso de cualquiera de los otros ViewResolvers, sin embargo, para fines pragmaticos el `BeanNameViewResolver` puede llegar a ser uno de los más útiles.

NOTE: Implementa un reporte de User Story y/o Task con JasoerReports usando `JasperReportsMultiFormatView`.

[small]#Powered by link:http://makingdevs.com/[MakingDevs.com]#
